(executable
 (name server)
 (libraries
  core
  async
  async_rpc_kernel
  async_rpc_websocket
  cohttp-async
  cohttp_static_handler
  core_unix.command_unix
  types
  market_data
  database
  parser
  pnl
  simulation
  bots
  arbitrage
  protocol)
 (flags
  (:standard -alert -do_not_spawn_domains -alert -unsafe_multidomain))
 (preprocess
  (pps ppx_jane)))
